//! Raw FFI bindings to statically-linked FBInk v1.25.0.
//!
//! Generated by bindgen from the vendored `fbink.h` at build time (see
//! `build.rs`). The safe wrapper lives in `signalkit::render::fbink`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// The soft-float Kindle/PW2 toolchain targets an older libc without getauxval,
// while current Rust std references it for stack probing. Returning 0 preserves
// the conservative fallback path in std and lets the legacy target link.
#[cfg(all(
    target_arch = "arm",
    target_os = "linux",
    target_env = "gnu",
    target_abi = "eabi"
))]
#[no_mangle]
pub extern "C" fn getauxval(_ty: ::std::os::raw::c_ulong) -> ::std::os::raw::c_ulong {
    0
}

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
