/* Generated by cbindgen from the `signalkit` crate. Do not edit by hand. */

#ifndef SIGNALKIT_H
#define SIGNALKIT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Opaque handles. Create with sk_*_new; release with the matching sk_*_free.
 * All calls must occur on the thread that created the sk_app. */
typedef struct sk_signal_i64 sk_signal_i64;
typedef struct sk_label sk_label;
typedef struct sk_button sk_button;
typedef struct sk_stack sk_stack;
typedef struct sk_app sk_app;

/* Library version string (static, do not free). */
const char *sk_version(void);

/* Last error message on this thread, or NULL. Valid until the next failing
 * call on the same thread. Do not free. */
const char *sk_last_error(void);

/* --- i64 signal --- */
sk_signal_i64 *sk_signal_i64_new(int64_t initial);
int64_t sk_signal_i64_get(const sk_signal_i64 *sig);
void sk_signal_i64_set(const sk_signal_i64 *sig, int64_t value);
void sk_signal_i64_free(sk_signal_i64 *sig);

/* --- label --- */
sk_label *sk_label_new(const char *text);
void sk_label_set_text(const sk_label *label, const char *text);
/* Binds the label's text to a signal, rendered as "<prefix><value><suffix>".
 * Applies the current value immediately, then updates on every change. */
void sk_label_bind_i64(const sk_label *label,
                       const sk_signal_i64 *sig,
                       const char *prefix,
                       const char *suffix);
void sk_label_free(sk_label *label);

/* --- button --- */
sk_button *sk_button_new(const char *title);
/* Registers a tap handler; user_data is passed back to cb on each tap. */
void sk_button_on_tap(const sk_button *button,
                      void (*cb)(void *user_data),
                      void *user_data);
void sk_button_free(sk_button *button);

/* --- stack --- */
sk_stack *sk_vstack_new(int spacing);
sk_stack *sk_hstack_new(int spacing);
void sk_stack_push_label(const sk_stack *stack, const sk_label *label);
void sk_stack_push_button(const sk_stack *stack, const sk_button *button);
void sk_stack_free(sk_stack *stack);

/* --- app --- */
/* Creates the app from a root stack (consumed) and a screen size. */
sk_app *sk_app_new(sk_stack *root, int width, int height);
/* Renders one frame. Returns 0 on success, -1 on error (see sk_last_error). */
int sk_app_render_frame(sk_app *app);
/* Dispatches a tap at (x, y) in screen pixels. Returns 1 if a handler ran. */
int sk_app_tap_at(sk_app *app, int x, int y);
void sk_app_free(sk_app *app);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* SIGNALKIT_H */
